### ISSUE TITLE
FrameFilterTest fails

### ISSUE THREAD

**Issue by mmccool** [thingweb/thingweb-directory#32]
gradle build fails (checkout from git of version 10.0.0) with the following output:

> Task :directory-core:test

org.eclipse.thingweb.directory.rdf.FrameFilterTest > testFilter FAILED
    java.lang.AssertionError at FrameFilterTest.groovy:25

21 tests completed, 1 failed, 3 skipped

> Task :directory-core:test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':directory-core:test'.
> There were failing tests. See the report at: file:///home/mmccool/Devel/thingweb-directory/directory-core/build/reports/tests/test/index.html

**Comment by mmccool** [comment]
Test report
[Test results - Test Summary.pdf](https://github.com/thingweb/thingweb-directory/files/2418229/Test.results.-.Test.Summary.pdf)

**Comment by mmccool** [comment]
This could be related to my, and could have the same cause/fix (eg OpenJDK vs Oracle)

**Comment by mmccool** [comment]
So I tried using the Oracle JDK (version 8 of course), build still fails in the same way.  This is a direct checkout from git, btw.   So... what dependency am I missing?  BTW I would be happy in the short term that just lets me disable that test... Anyway, here is the full output:
```
mmccool@upsq0:~/thing-directory/thingweb-directory$ gradle build
:directory-core:compileJava UP-TO-DATE
:directory-core:compileGroovy
Download https://repo1.maven.org/maven2/org/apache/httpcomponents/httpcore/4.4.4/httpcore-4.4.4.pom
Download https://repo1.maven.org/maven2/org/apache/httpcomponents/httpcomponents-core/4.4.4/httpcomponents-core-4.4.4.pom
:directory-core:processResources
:directory-core:classes
:directory-core:jar
:directory-servlet:compileJava
:directory-servlet:processResources UP-TO-DATE
:directory-servlet:classes
:directory-servlet:jar
:directory-app:compileJava
Download https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-server/9.4.12.v20180830/jetty-server-9.4.12.v20180830.pom
Download https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-project/9.4.12.v20180830/jetty-project-9.4.12.v20180830.pom
Download https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-webapp/9.4.12.v20180830/jetty-webapp-9.4.12.v20180830.pom
Download https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-http/9.4.12.v20180830/jetty-http-9.4.12.v20180830.pom
Download https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-io/9.4.12.v20180830/jetty-io-9.4.12.v20180830.pom
Download https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-xml/9.4.12.v20180830/jetty-xml-9.4.12.v20180830.pom
Download https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-servlet/9.4.12.v20180830/jetty-servlet-9.4.12.v20180830.pom
Download https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-util/9.4.12.v20180830/jetty-util-9.4.12.v20180830.pom
Download https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-security/9.4.12.v20180830/jetty-security-9.4.12.v20180830.pom
Download https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-server/9.4.12.v20180830/jetty-server-9.4.12.v20180830.jar
Download https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-webapp/9.4.12.v20180830/jetty-webapp-9.4.12.v20180830.jar
Download https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-http/9.4.12.v20180830/jetty-http-9.4.12.v20180830.jar
Download https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-io/9.4.12.v20180830/jetty-io-9.4.12.v20180830.jar
Download https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-xml/9.4.12.v20180830/jetty-xml-9.4.12.v20180830.jar
Download https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-servlet/9.4.12.v20180830/jetty-servlet-9.4.12.v20180830.jar
Download https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-util/9.4.12.v20180830/jetty-util-9.4.12.v20180830.jar
Download https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-security/9.4.12.v20180830/jetty-security-9.4.12.v20180830.jar
:directory-app:processWebApp
:directory-app:processResources
:directory-app:classes
:directory-app:jar
:directory-app:startScripts
:directory-app:distTar
:directory-app:distZip
:directory-app:assemble
:directory-app:compileTestJava UP-TO-DATE
:directory-app:processTestResources UP-TO-DATE
:directory-app:testClasses UP-TO-DATE
:directory-app:test UP-TO-DATE
:directory-app:check UP-TO-DATE
:directory-app:build
:directory-core:assemble
:directory-core:compileTestJava UP-TO-DATE
:directory-core:compileTestGroovy
:directory-core:processTestResources
:directory-core:testClasses
:directory-core:test

org.eclipse.thingweb.directory.rdf.SPARQLFilterTest > testFilter FAILED
    java.lang.AssertionError at SPARQLFilterTest.groovy:47

21 tests completed, 1 failed, 3 skipped
:directory-core:test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':directory-core:test'.
> There were failing tests. See the report at: file:///home/mmccool/thing-directory/thingweb-directory/directory-core/build/reports/tests/index.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 6 mins 2.366 secs
```

**Comment by mmccool** [comment]
With --info:
```
mmccool@upsq0:~/thing-directory/thingweb-directory$ gradle build --info
Starting Build
Settings evaluated using settings file '/home/mmccool/thing-directory/thingweb-directory/settings.gradle'.
Projects loaded. Root project using build file '/home/mmccool/thing-directory/thingweb-directory/build.gradle'.
Included projects: [root project 'thingweb-directory', project ':directory-app', project ':directory-coap', project ':directory-core', project ':directory-servlet']
Evaluating root project 'thingweb-directory' using build file '/home/mmccool/thing-directory/thingweb-directory/build.gradle'.
Evaluating project ':directory-app' using build file '/home/mmccool/thing-directory/thingweb-directory/directory-app/build.gradle'.
Evaluating project ':directory-coap' using build file '/home/mmccool/thing-directory/thingweb-directory/directory-coap/build.gradle'.
Evaluating project ':directory-core' using build file '/home/mmccool/thing-directory/thingweb-directory/directory-core/build.gradle'.
Evaluating project ':directory-servlet' using build file '/home/mmccool/thing-directory/thingweb-directory/directory-servlet/build.gradle'.
All projects evaluated.
Selected primary task 'build' from project :
Tasks to be executed: [task ':directory-core:compileJava', task ':directory-core:compileGroovy', task ':directory-core:processResources', task ':directory-core:classes', task ':directory-core:jar', task ':directory-servlet:compileJava', task ':directory-servlet:processResources', task ':directory-servlet:classes', task ':directory-servlet:jar', task ':directory-app:compileJava', task ':directory-app:processWebApp', task ':directory-app:processResources', task ':directory-app:classes', task ':directory-app:jar', task ':directory-app:startScripts', task ':directory-app:distTar', task ':directory-app:distZip', task ':directory-app:assemble', task ':directory-app:compileTestJava', task ':directory-app:processTestResources', task ':directory-app:testClasses', task ':directory-app:test', task ':directory-app:check', task ':directory-app:build', task ':directory-core:assemble', task ':directory-core:compileTestJava', task ':directory-core:compileTestGroovy', task ':directory-core:processTestResources', task ':directory-core:testClasses', task ':directory-core:test', task ':directory-core:check', task ':directory-core:build', task ':directory-servlet:war', task ':directory-servlet:assemble', task ':directory-servlet:compileTestJava', task ':directory-servlet:processTestResources', task ':directory-servlet:testClasses', task ':directory-servlet:test', task ':directory-servlet:check', task ':directory-servlet:build']
:directory-core:compileJava (Thread[main,5,main]) started.
:directory-core:compileJava
file or directory '/home/mmccool/thing-directory/thingweb-directory/directory-core/src/main/java', not found
Skipping task ':directory-core:compileJava' as it has no source files.
:directory-core:compileJava UP-TO-DATE
:directory-core:compileJava (Thread[main,5,main]) completed. Took 0.043 secs.
:directory-core:compileGroovy (Thread[main,5,main]) started.
:directory-core:compileGroovy
Skipping task ':directory-core:compileGroovy' as it is up-to-date (took 1.274 secs).
:directory-core:compileGroovy UP-TO-DATE
:directory-core:compileGroovy (Thread[main,5,main]) completed. Took 1.313 secs.
:directory-core:processResources (Thread[main,5,main]) started.
:directory-core:processResources
Skipping task ':directory-core:processResources' as it is up-to-date (took 0.012 secs).
:directory-core:processResources UP-TO-DATE
:directory-core:processResources (Thread[main,5,main]) completed. Took 0.023 secs.
:directory-core:classes (Thread[main,5,main]) started.
:directory-core:classes
Skipping task ':directory-core:classes' as it has no actions.
:directory-core:classes UP-TO-DATE
:directory-core:classes (Thread[main,5,main]) completed. Took 0.004 secs.
:directory-core:jar (Thread[main,5,main]) started.
:directory-core:jar
Skipping task ':directory-core:jar' as it is up-to-date (took 0.039 secs).
:directory-core:jar UP-TO-DATE
:directory-core:jar (Thread[main,5,main]) completed. Took 0.05 secs.
:directory-servlet:compileJava (Thread[main,5,main]) started.
:directory-servlet:compileJava
Skipping task ':directory-servlet:compileJava' as it is up-to-date (took 0.188 secs).
:directory-servlet:compileJava UP-TO-DATE
:directory-servlet:compileJava (Thread[main,5,main]) completed. Took 0.202 secs.
:directory-servlet:processResources (Thread[main,5,main]) started.
:directory-servlet:processResources
file or directory '/home/mmccool/thing-directory/thingweb-directory/directory-servlet/src/main/resources', not found
Skipping task ':directory-servlet:processResources' as it has no source files.
:directory-servlet:processResources UP-TO-DATE
:directory-servlet:processResources (Thread[main,5,main]) completed. Took 0.004 secs.
:directory-servlet:classes (Thread[main,5,main]) started.
:directory-servlet:classes
Skipping task ':directory-servlet:classes' as it has no actions.
:directory-servlet:classes UP-TO-DATE
:directory-servlet:classes (Thread[main,5,main]) completed. Took 0.003 secs.
:directory-servlet:jar (Thread[main,5,main]) started.
:directory-servlet:jar
Skipping task ':directory-servlet:jar' as it is up-to-date (took 0.008 secs).
:directory-servlet:jar UP-TO-DATE
:directory-servlet:jar (Thread[main,5,main]) completed. Took 0.013 secs.
:directory-app:compileJava (Thread[main,5,main]) started.
:directory-app:compileJava
Skipping task ':directory-app:compileJava' as it is up-to-date (took 0.17 secs).
:directory-app:compileJava UP-TO-DATE
:directory-app:compileJava (Thread[main,5,main]) completed. Took 0.176 secs.
:directory-app:processWebApp (Thread[main,5,main]) started.
:directory-app:processWebApp
Skipping task ':directory-app:processWebApp' as it is up-to-date (took 0.009 secs).
:directory-app:processWebApp UP-TO-DATE
:directory-app:processWebApp (Thread[main,5,main]) completed. Took 0.014 secs.
:directory-app:processResources (Thread[main,5,main]) started.
:directory-app:processResources
Skipping task ':directory-app:processResources' as it is up-to-date (took 0.015 secs).
:directory-app:processResources UP-TO-DATE
:directory-app:processResources (Thread[main,5,main]) completed. Took 0.022 secs.
:directory-app:classes (Thread[main,5,main]) started.
:directory-app:classes
Skipping task ':directory-app:classes' as it has no actions.
:directory-app:classes UP-TO-DATE
:directory-app:classes (Thread[main,5,main]) completed. Took 0.003 secs.
:directory-app:jar (Thread[main,5,main]) started.
:directory-app:jar
Skipping task ':directory-app:jar' as it is up-to-date (took 0.01 secs).
:directory-app:jar UP-TO-DATE
:directory-app:jar (Thread[main,5,main]) completed. Took 0.014 secs.
:directory-app:startScripts (Thread[main,5,main]) started.
:directory-app:startScripts
Skipping task ':directory-app:startScripts' as it is up-to-date (took 0.1 secs).
:directory-app:startScripts UP-TO-DATE
:directory-app:startScripts (Thread[main,5,main]) completed. Took 0.106 secs.
:directory-app:distTar (Thread[main,5,main]) started.
:directory-app:distTar
Skipping task ':directory-app:distTar' as it is up-to-date (took 0.029 secs).
:directory-app:distTar UP-TO-DATE
:directory-app:distTar (Thread[main,5,main]) completed. Took 0.044 secs.
:directory-app:distZip (Thread[main,5,main]) started.
:directory-app:distZip
Skipping task ':directory-app:distZip' as it is up-to-date (took 0.168 secs).
:directory-app:distZip UP-TO-DATE
:directory-app:distZip (Thread[main,5,main]) completed. Took 0.179 secs.
:directory-app:assemble (Thread[main,5,main]) started.
:directory-app:assemble
Skipping task ':directory-app:assemble' as it has no actions.
:directory-app:assemble UP-TO-DATE
:directory-app:assemble (Thread[main,5,main]) completed. Took 0.002 secs.
:directory-app:compileTestJava (Thread[main,5,main]) started.
:directory-app:compileTestJava
file or directory '/home/mmccool/thing-directory/thingweb-directory/directory-app/src/test/java', not found
Skipping task ':directory-app:compileTestJava' as it has no source files.
:directory-app:compileTestJava UP-TO-DATE
:directory-app:compileTestJava (Thread[main,5,main]) completed. Took 0.003 secs.
:directory-app:processTestResources (Thread[main,5,main]) started.
:directory-app:processTestResources
file or directory '/home/mmccool/thing-directory/thingweb-directory/directory-app/src/test/resources', not found
Skipping task ':directory-app:processTestResources' as it has no source files.
:directory-app:processTestResources UP-TO-DATE
:directory-app:processTestResources (Thread[main,5,main]) completed. Took 0.003 secs.
:directory-app:testClasses (Thread[main,5,main]) started.
:directory-app:testClasses
Skipping task ':directory-app:testClasses' as it has no actions.
:directory-app:testClasses UP-TO-DATE
:directory-app:testClasses (Thread[main,5,main]) completed. Took 0.002 secs.
:directory-app:test (Thread[main,5,main]) started.
:directory-app:test
file or directory '/home/mmccool/thing-directory/thingweb-directory/directory-app/build/classes/test', not found
Skipping task ':directory-app:test' as it has no source files.
:directory-app:test UP-TO-DATE
:directory-app:test (Thread[main,5,main]) completed. Took 0.003 secs.
:directory-app:check (Thread[main,5,main]) started.
:directory-app:check
Skipping task ':directory-app:check' as it has no actions.
:directory-app:check UP-TO-DATE
:directory-app:check (Thread[main,5,main]) completed. Took 0.002 secs.
:directory-app:build (Thread[main,5,main]) started.
:directory-app:build
Skipping task ':directory-app:build' as it has no actions.
:directory-app:build UP-TO-DATE
:directory-app:build (Thread[main,5,main]) completed. Took 0.003 secs.
:directory-core:assemble (Thread[main,5,main]) started.
:directory-core:assemble
Skipping task ':directory-core:assemble' as it has no actions.
:directory-core:assemble UP-TO-DATE
:directory-core:assemble (Thread[main,5,main]) completed. Took 0.002 secs.
:directory-core:compileTestJava (Thread[main,5,main]) started.
:directory-core:compileTestJava
file or directory '/home/mmccool/thing-directory/thingweb-directory/directory-core/src/test/java', not found
Skipping task ':directory-core:compileTestJava' as it has no source files.
:directory-core:compileTestJava UP-TO-DATE
:directory-core:compileTestJava (Thread[main,5,main]) completed. Took 0.003 secs.
:directory-core:compileTestGroovy (Thread[main,5,main]) started.
:directory-core:compileTestGroovy
Skipping task ':directory-core:compileTestGroovy' as it is up-to-date (took 0.178 secs).
:directory-core:compileTestGroovy UP-TO-DATE
:directory-core:compileTestGroovy (Thread[main,5,main]) completed. Took 0.187 secs.
:directory-core:processTestResources (Thread[main,5,main]) started.
:directory-core:processTestResources
Skipping task ':directory-core:processTestResources' as it is up-to-date (took 0.015 secs).
:directory-core:processTestResources UP-TO-DATE
:directory-core:processTestResources (Thread[main,5,main]) completed. Took 0.021 secs.
:directory-core:testClasses (Thread[main,5,main]) started.
:directory-core:testClasses
Skipping task ':directory-core:testClasses' as it has no actions.
:directory-core:testClasses UP-TO-DATE
:directory-core:testClasses (Thread[main,5,main]) completed. Took 0.005 secs.
:directory-core:test (Thread[main,5,main]) started.
:directory-core:test
Executing task ':directory-core:test' (up-to-date check took 0.158 secs) due to:
  No history is available.
Starting process 'Gradle Test Executor 1'. Working directory: /home/mmccool/thing-directory/thingweb-directory/directory-core Command: /usr/lib/jvm/java-8-openjdk-amd64/bin/java -Djava.security.manager=jarjar.org.gradle.process.internal.child.BootstrapSecurityManager -Dfile.encoding=UTF-8 -Duser.country=US -Duser.language=en -Duser.variant -ea -cp /home/mmccool/.gradle/caches/2.10/workerMain/gradle-worker.jar jarjar.org.gradle.process.internal.launcher.GradleWorkerMain 'Gradle Test Executor 1'
Successfully started process 'Gradle Test Executor 1'
Gradle Test Executor 1 started executing tests.

org.eclipse.thingweb.directory.ResourceManagerTest > testGet SKIPPED

org.eclipse.thingweb.directory.ResourceManagerTest > testRegister STANDARD_ERROR
    SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
    SLF4J: Defaulting to no-operation (NOP) logger implementation
    SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

org.eclipse.thingweb.directory.ResourceManagerTest > testReplace SKIPPED

org.eclipse.thingweb.directory.ResourceManagerTest > testLookUp SKIPPED

org.eclipse.thingweb.directory.rdf.FrameFilterTest STANDARD_ERROR
    Sep 28, 2018 1:41:38 PM java_util_logging_Logger$info$1 call
    INFO: Initializing transient in-memory RDF store (unique per JVM)...

org.eclipse.thingweb.directory.rdf.TDSerializerTest > testWriteLookUpResult STANDARD_ERROR
    Sep 28, 2018 1:41:41 PM java_util_logging_Logger$info$1 call
    INFO: Serializing resource as aggregation of TDs (e.g. lookup result)...

org.eclipse.thingweb.directory.rdf.TDSerializerTest > testWriteContent STANDARD_ERROR
    Sep 28, 2018 1:41:41 PM java_util_logging_Logger$info$1 call
    INFO: Serializing single TD resource...

org.eclipse.thingweb.directory.rdf.RepositoryFactoryTest > testGet STANDARD_ERROR
    Sep 28, 2018 1:41:41 PM java_util_logging_Logger$info$1 call
    INFO: Connecting to SPARQL endpoint from factory parameters...
    Sep 28, 2018 1:41:41 PM java_util_logging_Logger$info$1 call
    INFO: Sending probe request to SPARQL endpoint to test reachability...
    Sep 28, 2018 1:41:41 PM java_util_logging_Logger$warning$2 call
    WARNING: SPARQL endpoint cannot be reached

org.eclipse.thingweb.directory.rdf.SPARQLFilterTest > testFilter FAILED
    java.lang.AssertionError: SPARQL filter did not keep all resources. Expression: (filtered.size() == 2)
        at org.codehaus.groovy.runtime.InvokerHelper.assertFailed(InvokerHelper.java:417)
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.assertFailed(ScriptBytecodeAdapter.java:672)
        at org.eclipse.thingweb.directory.rdf.SPARQLFilterTest.testFilter(SPARQLFilterTest.groovy:47)
Gradle Test Executor 1 finished executing tests.

21 tests completed, 1 failed, 3 skipped
Finished generating test XML results (0.033 secs) into: /home/mmccool/thing-directory/thingweb-directory/directory-core/build/test-results
Generating HTML test report...
Finished generating test html results (0.101 secs) into: /home/mmccool/thing-directory/thingweb-directory/directory-core/build/reports/tests
:directory-core:test FAILED
:directory-core:test (Thread[main,5,main]) completed. Took 8.302 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':directory-core:test'.
> There were failing tests. See the report at: file:///home/mmccool/thing-directory/thingweb-directory/directory-core/build/reports/tests/index.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output.

BUILD FAILED

Total time: 27.409 secs
Stopped 0 compiler daemon(s).
```

**Comment by mmccool** [comment]
lt looks like it is looking for a SPARQL endpoint.   Do I need to be running a separate RDF database service, perhaps?
